// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_auth/firebase_auth.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSpVDJcok4cnOw9wTw5t1ALl5Mnq8ZeiA',
    appId: '1:114038359551:web:f4a5299164998507c513ca',
    messagingSenderId: '114038359551',
    projectId: 'summary-f9ac1',
    authDomain: 'summary-f9ac1.firebaseapp.com',
    storageBucket: 'summary-f9ac1.appspot.com',
    measurementId: 'G-KGZFY1SWZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK4ZZIf3zWkoaLX15KD_hpliOK4FtwTxw',
    appId: '1:114038359551:android:b686bc18c954b26dc513ca',
    messagingSenderId: '114038359551',
    projectId: 'summary-f9ac1',
    storageBucket: 'summary-f9ac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_2PU49UwfwonUWZyFVHii8VaZErIhvT4',
    appId: '1:114038359551:ios:2f44640b5ff53720c513ca',
    messagingSenderId: '114038359551',
    projectId: 'summary-f9ac1',
    storageBucket: 'summary-f9ac1.appspot.com',
    iosClientId:
        '114038359551-mjsa3115foqeeihs4rtcd70bb7ghdv8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.summary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_2PU49UwfwonUWZyFVHii8VaZErIhvT4',
    appId: '1:114038359551:ios:0c6e80fcc59065ffc513ca',
    messagingSenderId: '114038359551',
    projectId: 'summary-f9ac1',
    storageBucket: 'summary-f9ac1.appspot.com',
    iosClientId:
        '114038359551-rv4g86jdc3fkv42g3r56f40iepmm7ugg.apps.googleusercontent.com',
    iosBundleId: 'com.example.summary.RunnerTests',
  );
}
